CREATE TABLE IF NOT EXISTS users
(
    user_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR,
    email     VARCHAR,
    birthdate DATE
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id   INTEGER REFERENCES users (user_id),
    friend_id INTEGER REFERENCES users (user_id),
    CONSTRAINT pk_friends PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS rating
(
    rating_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name VARCHAR
);

CREATE TABLE IF NOT EXISTS films
(
    film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name    VARCHAR,
    description  VARCHAR,
    release_date DATE,
    duration_min INTEGER,
    rating       INTEGER REFERENCES rating (rating_id)
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR
);

CREATE TABLE IF NOT EXISTS films_genre
(
    film_id  INTEGER REFERENCES films (film_id),
    genre_id INTEGER REFERENCES genre (genre_id),
    PRIMARY KEY (film_id, genre_id)
);


CREATE TABLE IF NOT EXISTS likes
(
    film_id INTEGER REFERENCES films (film_id),
    user_id INTEGER REFERENCES users (user_id),
    PRIMARY KEY (film_id, user_id)
);
